version: '3.7'
services:
  node-express:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db
volumes:
  db:
